### ISSUE TITLE
bin folder missing

### ISSUE THREAD

**Issue by flightcomp** [dandar3/android-androidx-savedstate#1]
Errors occurred during the build.
Errors running builder 'Android Package Builder' on project '...'.
Resource '/.../bin' does not exist.

**Comment by dandar3** [comment]
@flightcomp 
`gen` is usually a more popular error than `bin` :-)

Can you go top menu `Project` > check `Build automatically` option and see if that solves it. 
If it doesn't do it automatically, after that try going `Project` > `Clean...` > `Clean all projects`

Is the project name `...` what you actually get as an error or did you simply left it out in the bug report?

Bwt, what version of Eclipse and Goole ADT plugin do you use? 
See `Help` > `About` for Eclipse versions and `Installation details` > `Installed software` > search for `Android`.

**Comment by flightcomp** [comment]
When I create the bin folder in the project compiles successfully. My
Eclipse ADT version is 24.2.0.201.60729

Roberto
